Style/ConditionalAssignment:
  Enabled: false
Metrics/LineLength:
  # This will disable the rule completely, regardless what other options you put
  Enabled: false
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - 'db/**/*'
    - 'features/**/*'
    - 'vendor/**/*'
