language: ruby
rvm:
  - 1.9.2
# uncomment this line if your project needs to run something other than `rake`:
before_script:
  - "mysql -e 'create database animal_test;'"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bundle exec rake db:drop db:create db:migrate spec cucumber