version: "3"

services:
  hospitium:
    container_name: "hospitium"
    image: hospitium
    build: "."
    # command: "sh start.sh"
    restart: "always"
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app/
    tty: true
