version: "3"

services:
  hospitium:
    container_name: "hospitium"
    image: hospitium
    build: "."
    user: "postgres"
    command: bash -l -c "service postgresql start; bundle exec rails server Puma -b 0.0.0.0 -p 3000;"
    restart: "always"
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - ./:/usr/src/app/
    tty: true
